global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - seiko_alertmanager:9093

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: seiko-backend
    static_configs:
      - targets:
          - seiko_backend:5000
    metrics_path: /metrics

  - job_name: alertmanager
    static_configs:
      - targets:
          - seiko_alertmanager:9093
